services:
  windows:
    image: xmoforf/windows
    container_name: windows
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - ./windows:/storage
    stop_grace_period: 2m
    restart: unless-stopped
